
services:
  - type: web
    name: flowstate-financeiro
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: https://api.render.com/deploy/srv-d5k450fpm1nc73fqfn40?key=aaAYJonr_ic
        sync: false
